### ISSUE TITLE
删除问题

### ISSUE THREAD

**Issue by xiaostrong** [goyourfly/MultiSelectAdapter#1]
在长按多选状态时，如果选中的第一个item不是recyclerview顶端的item，MultiSelectAdapter.getSelect()会为空。

**Comment by goyourfly** [comment]
已修复，Thank you

**Comment by xiaostrong** [comment]
@goyourfly Gradle 远程依赖还没更新么？只能在本地引用么？

**Comment by goyourfly** [comment]
@jiefangjun 更新了呀，3.2

**Comment by xiaostrong** [comment]
@goyourfly 好了，我刚看到，哈

**Comment by xiaostrong** [comment]
@goyourfly 更新过后，还是那样的情况，，不知道哪里出错了。。

**Comment by goyourfly** [comment]
compile 'com.github.goyourfly:MultiSelectAdapter:-SNAPSHOT'
试试这个

**Comment by xiaostrong** [comment]
好了，感谢
